### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by ERieger** [Ambience-Studios/ambience.css#9]
**Description of bug**
This is not so much a bug with the framework but rather the git repo congiuration.

I am trying to push some changes but it says that the branch is protected. Does this only apply to main branch. Should I branch then merge?

**How to Reproduce**
1. Create changes in main branch locally.
2. Commit changes.
3. Try to push.
4. See error in console or in popup window (vscode).

**Expected behavior**
Git will reject your attempt to push.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser N/A
 - Version Git: 2.25.1

**Comment by ERieger** [comment]
Not a bug, a feature. Please branch main before you make any changes, then create a PR.

**Comment by LCordial** [comment]
Sorry, for the confusion
